/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as CreateCampaignDetailsImport } from './routes/create-campaign-details'
import { Route as CampaignDetailsImport } from './routes/campaign-details'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const CreateCampaignDetailsRoute = CreateCampaignDetailsImport.update({
  path: '/create-campaign-details',
  getParentRoute: () => rootRoute,
} as any)

const CampaignDetailsRoute = CampaignDetailsImport.update({
  path: '/campaign-details',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/campaign-details': {
      preLoaderRoute: typeof CampaignDetailsImport
      parentRoute: typeof rootRoute
    }
    '/create-campaign-details': {
      preLoaderRoute: typeof CreateCampaignDetailsImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CampaignDetailsRoute,
  CreateCampaignDetailsRoute,
  ProfileRoute,
])

/* prettier-ignore-end */
